name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH deployment
        env: 
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER $}}
          SSH_HOST: ${{ secrets.SSH_HOST $}}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem $SSH_USER@$SSH_HOST -p 5022 <<EOF
            source ./nodevenv/public_html/todo-api/18/bin/activate
            git checkout master
            git pull
            npm install --omit=dev
            /usr/sbin/cloudlinux-selector restart --json --interpreter nodejs --app-root=/home/zwecbgyf/public_html/todo-api/
          EOF

          rm -f private_key.pem
    
